[package]
name = "bevy_dialogue"
version = "0.1.0"
authors = ["Trung Do <dothanhtrung@pm.me>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/kimtinh/bevy-dialogue"
keywords = ["bevy"]
description = "Bevy plugin for NPC's dialog"
exclude = ["assets", "examples", "tests", ".cargo", "rust-toolchain.toml"]
categories = ["game-development"]

[dependencies]
bevy = { version = ">=0.18", features = ["bevy_state", "bevy_asset"], default-features = false }
bevy_rand = { version = "0.14", default-features = false, features = ["wyrand"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
ron = { version = "0.12", default-features = false }
thiserror = { version = "2.0", default-features = false }
rand = { version = "0.10", default-features = false }

[target.'cfg(all(target_family = "wasm", any(target_os = "unknown", target_os = "none")))'.dependencies]
getrandom_03 = { version = "0.3", features = ["wasm_js"], package = "getrandom", optional = true }

[dev-dependencies]
bevy = { version = ">=0.18", features = ["dynamic_linking"] }
