[package]
name = "bevy_dialogue"
version = "0.4.2"
authors = ["Trung Do <dothanhtrung@pm.me>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/245project/bevy-plugin/bevy-dialogue"
keywords = ["bevy"]
description = "Bevy plugin for character dialogue"
exclude = ["assets", "examples", "tests", ".cargo", "rust-toolchain.toml"]
categories = ["game-development"]

[dependencies]
bevy = { version = ">=0.19", features = ["bevy_asset"], default-features = false }
bevy_rand = { version = ">=0.15", default-features = false, features = ["wyrand"] }
bevy_support_misc = { version = ">=0.9", default-features = false, features = ["ron_loader", "bin_loader"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
rand = { version = "0.10", default-features = false }
isolang = { version = "2.4", default-features = false, features = ["serde"] }
indexmap = { version = "2.14", default-features = false, features = ["std", "serde"] }

[features]
default = []
log = ["bevy/bevy_log"]

[dev-dependencies]
bevy = { version = ">=0.19", features = ["dynamic_linking"] }
